#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BOF_Guns

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BOF_Guns.BOF_Guns_C
// 0x0000 (0x00B0 - 0x00B0)
class UBOF_Guns_C final : public UBrickEditorObjectFilter
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BOF_Guns_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BOF_Guns_C")
	}
	static class UBOF_Guns_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBOF_Guns_C>();
	}
};
DUMPER7_ASSERTS_UBOF_Guns_C;

SDK_NAMESPACE_END
