#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BOF_Rods

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BOF_Rods.BOF_Rods_C
// 0x0000 (0x00B0 - 0x00B0)
class UBOF_Rods_C final : public UBrickEditorObjectFilter
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BOF_Rods_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BOF_Rods_C")
	}
	static class UBOF_Rods_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBOF_Rods_C>();
	}
};
DUMPER7_ASSERTS_UBOF_Rods_C;

SDK_NAMESPACE_END
