#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BOF_InputAndOutput

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BOF_InputAndOutput.BOF_InputAndOutput_C
// 0x0000 (0x00B0 - 0x00B0)
class UBOF_InputAndOutput_C final : public UBrickEditorObjectFilter
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BOF_InputAndOutput_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BOF_InputAndOutput_C")
	}
	static class UBOF_InputAndOutput_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBOF_InputAndOutput_C>();
	}
};
DUMPER7_ASSERTS_UBOF_InputAndOutput_C;

SDK_NAMESPACE_END
