#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AmmoBox_Missile

#include "Basic.hpp"

#include "BP_AmmoBox_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_AmmoBox_Missile.BP_AmmoBox_Missile_C
// 0x0000 (0x0278 - 0x0278)
class ABP_AmmoBox_Missile_C final : public ABP_AmmoBox_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_AmmoBox_Missile_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_AmmoBox_Missile_C")
	}
	static class ABP_AmmoBox_Missile_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_AmmoBox_Missile_C>();
	}
};
DUMPER7_ASSERTS_ABP_AmmoBox_Missile_C;

SDK_NAMESPACE_END
