#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AircraftR4

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_AircraftR4.BP_AircraftR4_C
// 0x0000 (0x0208 - 0x0208)
class UBP_AircraftR4_C final : public UMotorBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_AircraftR4_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_AircraftR4_C")
	}
	static class UBP_AircraftR4_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_AircraftR4_C>();
	}
};
DUMPER7_ASSERTS_UBP_AircraftR4_C;

SDK_NAMESPACE_END
