#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Actuator_1sx1sx2s_Bottom

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Actuator_1sx1sx2s_Bottom.BP_Actuator_1sx1sx2s_Bottom_C
// 0x0000 (0x01C0 - 0x01C0)
class UBP_Actuator_1sx1sx2s_Bottom_C final : public UActuatorBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Actuator_1sx1sx2s_Bottom_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Actuator_1sx1sx2s_Bottom_C")
	}
	static class UBP_Actuator_1sx1sx2s_Bottom_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Actuator_1sx1sx2s_Bottom_C>();
	}
};
DUMPER7_ASSERTS_UBP_Actuator_1sx1sx2s_Bottom_C;

SDK_NAMESPACE_END
