#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BladeHolder_2x1

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_BladeHolder_2x1.BP_BladeHolder_2x1_C
// 0x0000 (0x0190 - 0x0190)
class UBP_BladeHolder_2x1_C final : public UBladeHolderBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_BladeHolder_2x1_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_BladeHolder_2x1_C")
	}
	static class UBP_BladeHolder_2x1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_BladeHolder_2x1_C>();
	}
};
DUMPER7_ASSERTS_UBP_BladeHolder_2x1_C;

SDK_NAMESPACE_END
