#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Brick_10x4x1s

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Brick_10x4x1s.BP_Brick_10x4x1s_C
// 0x0000 (0x0190 - 0x0190)
class UBP_Brick_10x4x1s_C final : public UBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Brick_10x4x1s_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Brick_10x4x1s_C")
	}
	static class UBP_Brick_10x4x1s_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Brick_10x4x1s_C>();
	}
};
DUMPER7_ASSERTS_UBP_Brick_10x4x1s_C;

SDK_NAMESPACE_END
