#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BuildingDebris

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_BuildingDebris.BP_BuildingDebris_C
// 0x0000 (0x0270 - 0x0270)
class ABP_BuildingDebris_C final : public ABrickBuildingDebris
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_BuildingDebris_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_BuildingDebris_C")
	}
	static class ABP_BuildingDebris_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BuildingDebris_C>();
	}
};
DUMPER7_ASSERTS_ABP_BuildingDebris_C;

SDK_NAMESPACE_END
