#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Bricksville_Sign

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Bricksville_Sign.BP_Bricksville_Sign_C
// 0x0000 (0x0230 - 0x0230)
class ABP_Bricksville_Sign_C final : public AStaticMeshActor
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Bricksville_Sign_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Bricksville_Sign_C")
	}
	static class ABP_Bricksville_Sign_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Bricksville_Sign_C>();
	}
};
DUMPER7_ASSERTS_ABP_Bricksville_Sign_C;

SDK_NAMESPACE_END
