#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BrickCharacter_StaticInfo

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_BrickCharacter_StaticInfo.BP_BrickCharacter_StaticInfo_C
// 0x0000 (0x0300 - 0x0300)
class UBP_BrickCharacter_StaticInfo_C : public UCharacterStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_BrickCharacter_StaticInfo_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_BrickCharacter_StaticInfo_C")
	}
	static class UBP_BrickCharacter_StaticInfo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_BrickCharacter_StaticInfo_C>();
	}
};
DUMPER7_ASSERTS_UBP_BrickCharacter_StaticInfo_C;

SDK_NAMESPACE_END
