#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Billboard

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Billboard.BP_Billboard_C
// 0x0000 (0x0258 - 0x0258)
class ABP_Billboard_C final : public ABillboard
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Billboard_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Billboard_C")
	}
	static class ABP_Billboard_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Billboard_C>();
	}
};
DUMPER7_ASSERTS_ABP_Billboard_C;

SDK_NAMESPACE_END
