#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BrickVehicle

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_BrickVehicle.BP_BrickVehicle_C
// 0x0000 (0x0AC0 - 0x0AC0)
class ABP_BrickVehicle_C final : public ABrickVehicle
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_BrickVehicle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_BrickVehicle_C")
	}
	static class ABP_BrickVehicle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BrickVehicle_C>();
	}
};
DUMPER7_ASSERTS_ABP_BrickVehicle_C;

SDK_NAMESPACE_END
