#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BrickEditorArrowComponent

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_BrickEditorArrowComponent.BP_BrickEditorArrowComponent_C
// 0x0000 (0x0580 - 0x0580)
class UBP_BrickEditorArrowComponent_C final : public UBrickEditorArrowComponent
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_BrickEditorArrowComponent_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_BrickEditorArrowComponent_C")
	}
	static class UBP_BrickEditorArrowComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_BrickEditorArrowComponent_C>();
	}
};
DUMPER7_ASSERTS_UBP_BrickEditorArrowComponent_C;

SDK_NAMESPACE_END
