#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Bumper_4sx6x2

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Bumper_4sx6x2.BP_Bumper_4sx6x2_C
// 0x0000 (0x0190 - 0x0190)
class UBP_Bumper_4sx6x2_C final : public UBumperBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Bumper_4sx6x2_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Bumper_4sx6x2_C")
	}
	static class UBP_Bumper_4sx6x2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Bumper_4sx6x2_C>();
	}
};
DUMPER7_ASSERTS_UBP_Bumper_4sx6x2_C;

SDK_NAMESPACE_END
