#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CameraShake_Explosion

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_CameraShake_Explosion.BP_CameraShake_Explosion_C
// 0x0000 (0x01B0 - 0x01B0)
class UBP_CameraShake_Explosion_C final : public UMatineeCameraShake
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CameraShake_Explosion_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CameraShake_Explosion_C")
	}
	static class UBP_CameraShake_Explosion_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_CameraShake_Explosion_C>();
	}
};
DUMPER7_ASSERTS_UBP_CameraShake_Explosion_C;

SDK_NAMESPACE_END
