#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Coupling_1sx1sx1s_Front_Female

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Coupling_1sx1sx1s_Front_Female.BP_Coupling_1sx1sx1s_Front_Female_C
// 0x0000 (0x0190 - 0x0190)
class UBP_Coupling_1sx1sx1s_Front_Female_C final : public UCouplingBrickBaseStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Coupling_1sx1sx1s_Front_Female_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Coupling_1sx1sx1s_Front_Female_C")
	}
	static class UBP_Coupling_1sx1sx1s_Front_Female_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Coupling_1sx1sx1s_Front_Female_C>();
	}
};
DUMPER7_ASSERTS_UBP_Coupling_1sx1sx1s_Front_Female_C;

SDK_NAMESPACE_END
