#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CarHorn

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_CarHorn.BP_CarHorn_C
// 0x0000 (0x0060 - 0x0060)
class UBP_CarHorn_C final : public USirenType
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CarHorn_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CarHorn_C")
	}
	static class UBP_CarHorn_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_CarHorn_C>();
	}
};
DUMPER7_ASSERTS_UBP_CarHorn_C;

SDK_NAMESPACE_END
