#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Coupling_1x1x1s_Front_Male

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Coupling_1x1x1s_Front_Male.BP_Coupling_1x1x1s_Front_Male_C
// 0x0000 (0x01A0 - 0x01A0)
class UBP_Coupling_1x1x1s_Front_Male_C final : public UCouplingBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Coupling_1x1x1s_Front_Male_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Coupling_1x1x1s_Front_Male_C")
	}
	static class UBP_Coupling_1x1x1s_Front_Male_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Coupling_1x1x1s_Front_Male_C>();
	}
};
DUMPER7_ASSERTS_UBP_Coupling_1x1x1s_Front_Male_C;

SDK_NAMESPACE_END
