#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Coupling_4x1x2s_Top

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Coupling_4x1x2s_Top.BP_Coupling_4x1x2s_Top_C
// 0x0000 (0x0190 - 0x0190)
class UBP_Coupling_4x1x2s_Top_C final : public UCouplingBrickBaseStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Coupling_4x1x2s_Top_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Coupling_4x1x2s_Top_C")
	}
	static class UBP_Coupling_4x1x2s_Top_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Coupling_4x1x2s_Top_C>();
	}
};
DUMPER7_ASSERTS_UBP_Coupling_4x1x2s_Top_C;

SDK_NAMESPACE_END
