#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Camper

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Camper.BP_Camper_C
// 0x0000 (0x0240 - 0x0240)
class ABP_Camper_C final : public AStaticMeshProp
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Camper_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Camper_C")
	}
	static class ABP_Camper_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Camper_C>();
	}
};
DUMPER7_ASSERTS_ABP_Camper_C;

SDK_NAMESPACE_END
