#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DoubleFlash_Category

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_DoubleFlash_Category.BP_DoubleFlash_Category_C
// 0x0000 (0x0080 - 0x0080)
class UBP_DoubleFlash_Category_C : public USirenSequence
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DoubleFlash_Category_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DoubleFlash_Category_C")
	}
	static class UBP_DoubleFlash_Category_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_DoubleFlash_Category_C>();
	}
};
DUMPER7_ASSERTS_UBP_DoubleFlash_Category_C;

SDK_NAMESPACE_END
