#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DragWheel_4x2

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_DragWheel_4x2.BP_DragWheel_4x2_C
// 0x0000 (0x01D0 - 0x01D0)
class UBP_DragWheel_4x2_C final : public UCarWheelBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DragWheel_4x2_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DragWheel_4x2_C")
	}
	static class UBP_DragWheel_4x2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_DragWheel_4x2_C>();
	}
};
DUMPER7_ASSERTS_UBP_DragWheel_4x2_C;

SDK_NAMESPACE_END
