#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DisplayBrick

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_DisplayBrick.BP_DisplayBrick_C
// 0x0000 (0x01D0 - 0x01D0)
class UBP_DisplayBrick_C final : public UDisplayBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DisplayBrick_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DisplayBrick_C")
	}
	static class UBP_DisplayBrick_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_DisplayBrick_C>();
	}
};
DUMPER7_ASSERTS_UBP_DisplayBrick_C;

SDK_NAMESPACE_END
