#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DragV8

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_DragV8.BP_DragV8_C
// 0x0000 (0x0208 - 0x0208)
class UBP_DragV8_C final : public UMotorBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DragV8_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DragV8_C")
	}
	static class UBP_DragV8_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_DragV8_C>();
	}
};
DUMPER7_ASSERTS_UBP_DragV8_C;

SDK_NAMESPACE_END
