#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Dumpster

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Dumpster.BP_Dumpster_C
// 0x0008 (0x0238 - 0x0230)
class ABP_Dumpster_C final : public AStaticMeshActor
{
public:
	struct FRandomStream                          RandomStream;                                      // 0x0230(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Dumpster_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Dumpster_C")
	}
	static class ABP_Dumpster_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Dumpster_C>();
	}
};
DUMPER7_ASSERTS_ABP_Dumpster_C;

SDK_NAMESPACE_END
