#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ExhaustCylinder

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ExhaustCylinder.BP_ExhaustCylinder_C
// 0x0000 (0x01D8 - 0x01D8)
class UBP_ExhaustCylinder_C final : public UExhaustBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ExhaustCylinder_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ExhaustCylinder_C")
	}
	static class UBP_ExhaustCylinder_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ExhaustCylinder_C>();
	}
};
DUMPER7_ASSERTS_UBP_ExhaustCylinder_C;

SDK_NAMESPACE_END
