#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ExhaustBrick

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ExhaustBrick.BP_ExhaustBrick_C
// 0x0000 (0x01D8 - 0x01D8)
class UBP_ExhaustBrick_C final : public UExhaustBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ExhaustBrick_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ExhaustBrick_C")
	}
	static class UBP_ExhaustBrick_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ExhaustBrick_C>();
	}
};
DUMPER7_ASSERTS_UBP_ExhaustBrick_C;

SDK_NAMESPACE_END
