#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Editor_Hangar

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Editor_Hangar.BP_Editor_Hangar_C
// 0x0000 (0x0340 - 0x0340)
class ABP_Editor_Hangar_C final : public AGarage
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Editor_Hangar_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Editor_Hangar_C")
	}
	static class ABP_Editor_Hangar_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Editor_Hangar_C>();
	}
};
DUMPER7_ASSERTS_ABP_Editor_Hangar_C;

SDK_NAMESPACE_END
