#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FireExtinguisher

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_FireExtinguisher.BP_FireExtinguisher_C
// 0x0000 (0x0278 - 0x0278)
class ABP_FireExtinguisher_C final : public AFireExtinguisher
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_FireExtinguisher_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_FireExtinguisher_C")
	}
	static class ABP_FireExtinguisher_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_FireExtinguisher_C>();
	}
};
DUMPER7_ASSERTS_ABP_FireExtinguisher_C;

SDK_NAMESPACE_END
