#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FireExtinguisher_StaticInfo

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_FireExtinguisher_StaticInfo.BP_FireExtinguisher_StaticInfo_C
// 0x0000 (0x04E0 - 0x04E0)
class UBP_FireExtinguisher_StaticInfo_C final : public UFireExtinguisherStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_FireExtinguisher_StaticInfo_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_FireExtinguisher_StaticInfo_C")
	}
	static class UBP_FireExtinguisher_StaticInfo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_FireExtinguisher_StaticInfo_C>();
	}
};
DUMPER7_ASSERTS_UBP_FireExtinguisher_StaticInfo_C;

SDK_NAMESPACE_END
