#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Float

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Float.BP_Float_C
// 0x0000 (0x01D0 - 0x01D0)
class UBP_Float_C final : public UFloatBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Float_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Float_C")
	}
	static class UBP_Float_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Float_C>();
	}
};
DUMPER7_ASSERTS_UBP_Float_C;

SDK_NAMESPACE_END
