#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GasStation

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_GasStation.BP_GasStation_C
// 0x0000 (0x02C0 - 0x02C0)
class ABP_GasStation_C final : public ABrickBuilding
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_GasStation_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_GasStation_C")
	}
	static class ABP_GasStation_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_GasStation_C>();
	}
};
DUMPER7_ASSERTS_ABP_GasStation_C;

SDK_NAMESPACE_END
