#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GridZylinder_2x2x1s

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_GridZylinder_2x2x1s.BP_GridZylinder_2x2x1s_C
// 0x0000 (0x0190 - 0x0190)
class UBP_GridZylinder_2x2x1s_C final : public UGrilleBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_GridZylinder_2x2x1s_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_GridZylinder_2x2x1s_C")
	}
	static class UBP_GridZylinder_2x2x1s_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_GridZylinder_2x2x1s_C>();
	}
};
DUMPER7_ASSERTS_UBP_GridZylinder_2x2x1s_C;

SDK_NAMESPACE_END
