#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Garage_01

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Garage_01.BP_Garage_01_C
// 0x0000 (0x02C0 - 0x02C0)
class ABP_Garage_01_C final : public ABrickBuilding
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Garage_01_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Garage_01_C")
	}
	static class ABP_Garage_01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Garage_01_C>();
	}
};
DUMPER7_ASSERTS_ABP_Garage_01_C;

SDK_NAMESPACE_END
