#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Handle_1x2x4s

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Handle_1x2x4s.BP_Handle_1x2x4s_C
// 0x0000 (0x0190 - 0x0190)
class UBP_Handle_1x2x4s_C final : public UHandleBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Handle_1x2x4s_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Handle_1x2x4s_C")
	}
	static class UBP_Handle_1x2x4s_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Handle_1x2x4s_C>();
	}
};
DUMPER7_ASSERTS_UBP_Handle_1x2x4s_C;

SDK_NAMESPACE_END
