#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_IdlerWheel

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_IdlerWheel.BP_IdlerWheel_C
// 0x0000 (0x01B0 - 0x01B0)
class UBP_IdlerWheel_C final : public UIdlerWheelBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_IdlerWheel_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_IdlerWheel_C")
	}
	static class UBP_IdlerWheel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_IdlerWheel_C>();
	}
};
DUMPER7_ASSERTS_UBP_IdlerWheel_C;

SDK_NAMESPACE_END
