#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ImageCylinder

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ImageCylinder.BP_ImageCylinder_C
// 0x0000 (0x01E0 - 0x01E0)
class UBP_ImageCylinder_C final : public UImageBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ImageCylinder_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ImageCylinder_C")
	}
	static class UBP_ImageCylinder_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ImageCylinder_C>();
	}
};
DUMPER7_ASSERTS_UBP_ImageCylinder_C;

SDK_NAMESPACE_END
