#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LightRampRounded

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_LightRampRounded.BP_LightRampRounded_C
// 0x0000 (0x01D8 - 0x01D8)
class UBP_LightRampRounded_C final : public ULightBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_LightRampRounded_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_LightRampRounded_C")
	}
	static class UBP_LightRampRounded_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_LightRampRounded_C>();
	}
};
DUMPER7_ASSERTS_UBP_LightRampRounded_C;

SDK_NAMESPACE_END
