#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LightCone

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_LightCone.BP_LightCone_C
// 0x0000 (0x01D8 - 0x01D8)
class UBP_LightCone_C final : public ULightBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_LightCone_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_LightCone_C")
	}
	static class UBP_LightCone_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_LightCone_C>();
	}
};
DUMPER7_ASSERTS_UBP_LightCone_C;

SDK_NAMESPACE_END
