#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LandingGear_2x2x2

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_LandingGear_2x2x2.BP_LandingGear_2x2x2_C
// 0x0000 (0x0198 - 0x0198)
class UBP_LandingGear_2x2x2_C final : public UAxleBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_LandingGear_2x2x2_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_LandingGear_2x2x2_C")
	}
	static class UBP_LandingGear_2x2x2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_LandingGear_2x2x2_C>();
	}
};
DUMPER7_ASSERTS_UBP_LandingGear_2x2x2_C;

SDK_NAMESPACE_END
