#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Launcher

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Launcher.BP_Launcher_C
// 0x0000 (0x02B0 - 0x02B0)
class ABP_Launcher_C final : public AFirearm
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Launcher_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Launcher_C")
	}
	static class ABP_Launcher_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Launcher_C>();
	}
};
DUMPER7_ASSERTS_ABP_Launcher_C;

SDK_NAMESPACE_END
