#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LightHemisphere

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_LightHemisphere.BP_LightHemisphere_C
// 0x0000 (0x01D8 - 0x01D8)
class UBP_LightHemisphere_C final : public ULightBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_LightHemisphere_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_LightHemisphere_C")
	}
	static class UBP_LightHemisphere_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_LightHemisphere_C>();
	}
};
DUMPER7_ASSERTS_UBP_LightHemisphere_C;

SDK_NAMESPACE_END
