#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Launcher_2x1sx1s

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Launcher_2x1sx1s.BP_Launcher_2x1sx1s_C
// 0x0000 (0x02C0 - 0x02C0)
class UBP_Launcher_2x1sx1s_C final : public ULauncherBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Launcher_2x1sx1s_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Launcher_2x1sx1s_C")
	}
	static class UBP_Launcher_2x1sx1s_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Launcher_2x1sx1s_C>();
	}
};
DUMPER7_ASSERTS_UBP_Launcher_2x1sx1s_C;

SDK_NAMESPACE_END
