#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Missile_Large

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Missile_Large.BP_Missile_Large_C
// 0x0000 (0x0400 - 0x0400)
class ABP_Missile_Large_C : public ABrickProjectile
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Missile_Large_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Missile_Large_C")
	}
	static class ABP_Missile_Large_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Missile_Large_C>();
	}
};
DUMPER7_ASSERTS_ABP_Missile_Large_C;

SDK_NAMESPACE_END
