#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MathBrick

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_MathBrick.BP_MathBrick_C
// 0x0000 (0x01D0 - 0x01D0)
class UBP_MathBrick_C final : public UMathBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_MathBrick_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_MathBrick_C")
	}
	static class UBP_MathBrick_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_MathBrick_C>();
	}
};
DUMPER7_ASSERTS_UBP_MathBrick_C;

SDK_NAMESPACE_END
