#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MenuGameMode

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_MenuGameMode.BP_MenuGameMode_C
// 0x0008 (0x0338 - 0x0330)
class ABP_MenuGameMode_C final : public AMenuGameMode
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0330(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_MenuGameMode_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_MenuGameMode_C")
	}
	static class ABP_MenuGameMode_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_MenuGameMode_C>();
	}
};
DUMPER7_ASSERTS_ABP_MenuGameMode_C;

SDK_NAMESPACE_END
