#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MK18

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_MK18.BP_MK18_C
// 0x0000 (0x02B0 - 0x02B0)
class ABP_MK18_C final : public AFirearm
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_MK18_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_MK18_C")
	}
	static class ABP_MK18_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_MK18_C>();
	}
};
DUMPER7_ASSERTS_ABP_MK18_C;

SDK_NAMESPACE_END
