#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MenuFunctionLibrary

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_MenuFunctionLibrary.BP_MenuFunctionLibrary_C
// 0x0000 (0x0028 - 0x0028)
class UBP_MenuFunctionLibrary_C final : public UBlueprintFunctionLibrary
{
public:
	static class UMenuButtonWidget* CreateBackButton(class UMenuButtonPanelWidget* Widget, const TDelegate<void()>& Delegate, class UObject* __WorldContext);
	static class UMenuButtonWidget* CreateApplyButton(class UMenuButtonPanelWidget* Widget, const TDelegate<void()>& Delegate, class UObject* __WorldContext);
	static class UMenuButtonWidget* CreateConfirmButton(class UMenuButtonPanelWidget* Widget, const TDelegate<void()>& Delegate, class UObject* __WorldContext);
	static class UMenuButtonWidget* CreateCancelButton(class UMenuButtonPanelWidget* Widget, const TDelegate<void()>& Delegate, class UObject* __WorldContext);
	static class UMenuButtonWidget* CreateExitButton(class UMenuButtonPanelWidget* Widget, const TDelegate<void()>& Delegate, class UObject* __WorldContext);
	static class UMenuButtonWidget* CreateContinueButton(class UMenuButtonPanelWidget* Widget, const TDelegate<void()>& Delegate, class UObject* __WorldContext);
	static class UMenuButtonWidget* CreateRefreshButton(class UMenuButtonPanelWidget* Widget, const TDelegate<void()>& Delegate, class UObject* __WorldContext);
	static class UMenuButtonWidget* CreateRetryButton(class UMenuButtonPanelWidget* Widget, const TDelegate<void()>& Delegate, class UObject* __WorldContext);
	static class UMenuButtonWidget* CreateShowProfileButton(class UMenuButtonPanelWidget* Widget, const TDelegate<void()>& Delegate, class UObject* __WorldContext);
	static class UMenuButtonWidget* CreateRevertButton(class UMenuButtonPanelWidget* Widget, const TDelegate<void()>& Delegate, class UObject* __WorldContext);
	static class UMenuButtonWidget* CreateEditButton(class UMenuButtonPanelWidget* Widget, const TDelegate<void()>& Delegate, class UObject* __WorldContext);
	static class UMenuButtonWidget* CreateViewInBrowserButton(class UMenuButtonPanelWidget* Widget, const TDelegate<void()>& Delegate, class UObject* __WorldContext);
	static class UMenuButtonWidget* CreateImportButton(class UMenuButtonPanelWidget* Widget, const TDelegate<void()>& Delegate, class UObject* __WorldContext);
	static class UMenuButtonWidget* CreateDisplayModeButton(class UMenuButtonPanelWidget* Widget, const TDelegate<void()>& Delegate, class UObject* __WorldContext);
	static class UMenuButtonWidget* CreateLinkButton(class UMenuButtonPanelWidget* Widget, const class FText& DisplayText, const TDelegate<void()>& Delegate, class UObject* __WorldContext);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_MenuFunctionLibrary_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_MenuFunctionLibrary_C")
	}
	static class UBP_MenuFunctionLibrary_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_MenuFunctionLibrary_C>();
	}
};
DUMPER7_ASSERTS_UBP_MenuFunctionLibrary_C;

SDK_NAMESPACE_END
