#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Motor_4x2x5s

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Motor_4x2x5s.BP_Motor_4x2x5s_C
// 0x0000 (0x0208 - 0x0208)
class UBP_Motor_4x2x5s_C final : public UMotorBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Motor_4x2x5s_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Motor_4x2x5s_C")
	}
	static class UBP_Motor_4x2x5s_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Motor_4x2x5s_C>();
	}
};
DUMPER7_ASSERTS_UBP_Motor_4x2x5s_C;

SDK_NAMESPACE_END
