#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Octagon_2x4x4

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Octagon_2x4x4.BP_Octagon_2x4x4_C
// 0x0000 (0x0190 - 0x0190)
class UBP_Octagon_2x4x4_C final : public URedirectorBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Octagon_2x4x4_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Octagon_2x4x4_C")
	}
	static class UBP_Octagon_2x4x4_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Octagon_2x4x4_C>();
	}
};
DUMPER7_ASSERTS_UBP_Octagon_2x4x4_C;

SDK_NAMESPACE_END
