#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PizzaPalace

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_PizzaPalace.BP_PizzaPalace_C
// 0x0000 (0x02C0 - 0x02C0)
class ABP_PizzaPalace_C final : public ABrickBuilding
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PizzaPalace_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PizzaPalace_C")
	}
	static class ABP_PizzaPalace_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PizzaPalace_C>();
	}
};
DUMPER7_ASSERTS_ABP_PizzaPalace_C;

SDK_NAMESPACE_END
