#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Pants_Desert

#include "Basic.hpp"

#include "BP_Pants_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Pants_Desert.BP_Pants_Desert_C
// 0x0000 (0x02A8 - 0x02A8)
class ABP_Pants_Desert_C final : public ABP_Pants_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Pants_Desert_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Pants_Desert_C")
	}
	static class ABP_Pants_Desert_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Pants_Desert_C>();
	}
};
DUMPER7_ASSERTS_ABP_Pants_Desert_C;

SDK_NAMESPACE_END
