#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Paint_Tan

#include "Basic.hpp"

#include "BP_Paint_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Paint_Tan.BP_Paint_Tan_C
// 0x0000 (0x02B0 - 0x02B0)
class ABP_Paint_Tan_C final : public ABP_Paint_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Paint_Tan_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Paint_Tan_C")
	}
	static class ABP_Paint_Tan_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Paint_Tan_C>();
	}
};
DUMPER7_ASSERTS_ABP_Paint_Tan_C;

SDK_NAMESPACE_END
