#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Prop_5x1

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Prop_5x1.BP_Prop_5x1_C
// 0x0000 (0x0198 - 0x0198)
class UBP_Prop_5x1_C final : public UPropellerBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Prop_5x1_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Prop_5x1_C")
	}
	static class UBP_Prop_5x1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Prop_5x1_C>();
	}
};
DUMPER7_ASSERTS_UBP_Prop_5x1_C;

SDK_NAMESPACE_END
