#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PlaneTail_10x10x16

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_PlaneTail_10x10x16.BP_PlaneTail_10x10x16_C
// 0x0000 (0x0190 - 0x0190)
class UBP_PlaneTail_10x10x16_C final : public UTailBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PlaneTail_10x10x16_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PlaneTail_10x10x16_C")
	}
	static class UBP_PlaneTail_10x10x16_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_PlaneTail_10x10x16_C>();
	}
};
DUMPER7_ASSERTS_UBP_PlaneTail_10x10x16_C;

SDK_NAMESPACE_END
