#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RaceTimer

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_RaceTimer.BP_RaceTimer_C
// 0x0000 (0x0230 - 0x0230)
class ABP_RaceTimer_C final : public ARaceTimer
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_RaceTimer_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_RaceTimer_C")
	}
	static class ABP_RaceTimer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_RaceTimer_C>();
	}
};
DUMPER7_ASSERTS_ABP_RaceTimer_C;

SDK_NAMESPACE_END
