#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RC_Sequence_CloseUp

#include "Basic.hpp"

#include "BP_RC_Sequence_2_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_RC_Sequence_CloseUp.BP_RC_Sequence_CloseUp_C
// 0x0000 (0x02A0 - 0x02A0)
class ABP_RC_Sequence_CloseUp_C final : public ABP_RC_Sequence_2_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_RC_Sequence_CloseUp_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_RC_Sequence_CloseUp_C")
	}
	static class ABP_RC_Sequence_CloseUp_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_RC_Sequence_CloseUp_C>();
	}
};
DUMPER7_ASSERTS_ABP_RC_Sequence_CloseUp_C;

SDK_NAMESPACE_END
