#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Rod_1x1x20

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Rod_1x1x20.BP_Rod_1x1x20_C
// 0x0000 (0x0190 - 0x0190)
class UBP_Rod_1x1x20_C final : public URodBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Rod_1x1x20_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Rod_1x1x20_C")
	}
	static class UBP_Rod_1x1x20_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Rod_1x1x20_C>();
	}
};
DUMPER7_ASSERTS_UBP_Rod_1x1x20_C;

SDK_NAMESPACE_END
