#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RedirectorZylinder_2x2x1s_02

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_RedirectorZylinder_2x2x1s_02.BP_RedirectorZylinder_2x2x1s_02_C
// 0x0000 (0x0190 - 0x0190)
class UBP_RedirectorZylinder_2x2x1s_02_C final : public URedirectorBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_RedirectorZylinder_2x2x1s_02_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_RedirectorZylinder_2x2x1s_02_C")
	}
	static class UBP_RedirectorZylinder_2x2x1s_02_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_RedirectorZylinder_2x2x1s_02_C>();
	}
};
DUMPER7_ASSERTS_UBP_RedirectorZylinder_2x2x1s_02_C;

SDK_NAMESPACE_END
