#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RandomSpawnArea

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_RandomSpawnArea.BP_RandomSpawnArea_C
// 0x0000 (0x0260 - 0x0260)
class ABP_RandomSpawnArea_C final : public ASpawnArea
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_RandomSpawnArea_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_RandomSpawnArea_C")
	}
	static class ABP_RandomSpawnArea_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_RandomSpawnArea_C>();
	}
};
DUMPER7_ASSERTS_ABP_RandomSpawnArea_C;

SDK_NAMESPACE_END
