#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SkyScraper_Small

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SkyScraper_Small.BP_SkyScraper_Small_C
// 0x0000 (0x02C0 - 0x02C0)
class ABP_SkyScraper_Small_C final : public ABrickBuilding
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SkyScraper_Small_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SkyScraper_Small_C")
	}
	static class ABP_SkyScraper_Small_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SkyScraper_Small_C>();
	}
};
DUMPER7_ASSERTS_ABP_SkyScraper_Small_C;

SDK_NAMESPACE_END
