#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Seat_3x2x2

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Seat_3x2x2.BP_Seat_3x2x2_C
// 0x0000 (0x01E8 - 0x01E8)
class UBP_Seat_3x2x2_C final : public USeatBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Seat_3x2x2_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Seat_3x2x2_C")
	}
	static class UBP_Seat_3x2x2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Seat_3x2x2_C>();
	}
};
DUMPER7_ASSERTS_UBP_Seat_3x2x2_C;

SDK_NAMESPACE_END
