#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Sniper_StaticInfo

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Sniper_StaticInfo.BP_Sniper_StaticInfo_C
// 0x0000 (0x0810 - 0x0810)
class UBP_Sniper_StaticInfo_C final : public UFirearmStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Sniper_StaticInfo_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Sniper_StaticInfo_C")
	}
	static class UBP_Sniper_StaticInfo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Sniper_StaticInfo_C>();
	}
};
DUMPER7_ASSERTS_UBP_Sniper_StaticInfo_C;

SDK_NAMESPACE_END
