#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SniperScope_StaticInfo

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SniperScope_StaticInfo.BP_SniperScope_StaticInfo_C
// 0x0000 (0x0400 - 0x0400)
class UBP_SniperScope_StaticInfo_C final : public USightStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SniperScope_StaticInfo_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SniperScope_StaticInfo_C")
	}
	static class UBP_SniperScope_StaticInfo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SniperScope_StaticInfo_C>();
	}
};
DUMPER7_ASSERTS_UBP_SniperScope_StaticInfo_C;

SDK_NAMESPACE_END
