#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ScalableZylinder

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ScalableZylinder.BP_ScalableZylinder_C
// 0x0000 (0x01D0 - 0x01D0)
class UBP_ScalableZylinder_C final : public UScalableBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ScalableZylinder_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ScalableZylinder_C")
	}
	static class UBP_ScalableZylinder_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ScalableZylinder_C>();
	}
};
DUMPER7_ASSERTS_UBP_ScalableZylinder_C;

SDK_NAMESPACE_END
