#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Shirt

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Shirt.BP_Shirt_C
// 0x0000 (0x02A8 - 0x02A8)
class ABP_Shirt_C : public AWearable
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Shirt_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Shirt_C")
	}
	static class ABP_Shirt_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Shirt_C>();
	}
};
DUMPER7_ASSERTS_ABP_Shirt_C;

SDK_NAMESPACE_END
