#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ScalableCornerRounded

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ScalableCornerRounded.BP_ScalableCornerRounded_C
// 0x0000 (0x01D0 - 0x01D0)
class UBP_ScalableCornerRounded_C final : public UScalableBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ScalableCornerRounded_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ScalableCornerRounded_C")
	}
	static class UBP_ScalableCornerRounded_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ScalableCornerRounded_C>();
	}
};
DUMPER7_ASSERTS_UBP_ScalableCornerRounded_C;

SDK_NAMESPACE_END
