#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Shirt_StaticInfo

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Shirt_StaticInfo.BP_Shirt_StaticInfo_C
// 0x0000 (0x03A0 - 0x03A0)
class UBP_Shirt_StaticInfo_C final : public UWearableStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Shirt_StaticInfo_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Shirt_StaticInfo_C")
	}
	static class UBP_Shirt_StaticInfo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Shirt_StaticInfo_C>();
	}
};
DUMPER7_ASSERTS_UBP_Shirt_StaticInfo_C;

SDK_NAMESPACE_END
