#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Suppressor

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Suppressor.BP_Suppressor_C
// 0x0000 (0x0270 - 0x0270)
class ABP_Suppressor_C final : public ABarrelAttachment
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Suppressor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Suppressor_C")
	}
	static class ABP_Suppressor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Suppressor_C>();
	}
};
DUMPER7_ASSERTS_ABP_Suppressor_C;

SDK_NAMESPACE_END
