#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ScalableWedgeCorner

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ScalableWedgeCorner.BP_ScalableWedgeCorner_C
// 0x0000 (0x01D0 - 0x01D0)
class UBP_ScalableWedgeCorner_C final : public UScalableBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ScalableWedgeCorner_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ScalableWedgeCorner_C")
	}
	static class UBP_ScalableWedgeCorner_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ScalableWedgeCorner_C>();
	}
};
DUMPER7_ASSERTS_UBP_ScalableWedgeCorner_C;

SDK_NAMESPACE_END
