#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ScalableHalfCylinder

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ScalableHalfCylinder.BP_ScalableHalfCylinder_C
// 0x0000 (0x01D0 - 0x01D0)
class UBP_ScalableHalfCylinder_C final : public UScalableBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ScalableHalfCylinder_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ScalableHalfCylinder_C")
	}
	static class UBP_ScalableHalfCylinder_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ScalableHalfCylinder_C>();
	}
};
DUMPER7_ASSERTS_UBP_ScalableHalfCylinder_C;

SDK_NAMESPACE_END
