#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Shirt_Tan

#include "Basic.hpp"

#include "BP_Shirt_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Shirt_Tan.BP_Shirt_Tan_C
// 0x0000 (0x02A8 - 0x02A8)
class ABP_Shirt_Tan_C final : public ABP_Shirt_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Shirt_Tan_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Shirt_Tan_C")
	}
	static class ABP_Shirt_Tan_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Shirt_Tan_C>();
	}
};
DUMPER7_ASSERTS_ABP_Shirt_Tan_C;

SDK_NAMESPACE_END
