#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SwitchBrick

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SwitchBrick.BP_SwitchBrick_C
// 0x0000 (0x01D0 - 0x01D0)
class UBP_SwitchBrick_C final : public USwitchBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SwitchBrick_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SwitchBrick_C")
	}
	static class UBP_SwitchBrick_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SwitchBrick_C>();
	}
};
DUMPER7_ASSERTS_UBP_SwitchBrick_C;

SDK_NAMESPACE_END
