#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ScalableCornerRoundedN

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ScalableCornerRoundedN.BP_ScalableCornerRoundedN_C
// 0x0000 (0x01D0 - 0x01D0)
class UBP_ScalableCornerRoundedN_C final : public UScalableBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ScalableCornerRoundedN_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ScalableCornerRoundedN_C")
	}
	static class UBP_ScalableCornerRoundedN_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ScalableCornerRoundedN_C>();
	}
};
DUMPER7_ASSERTS_UBP_ScalableCornerRoundedN_C;

SDK_NAMESPACE_END
