#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SensorBrick

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SensorBrick.BP_SensorBrick_C
// 0x0000 (0x01D0 - 0x01D0)
class UBP_SensorBrick_C final : public USensorBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SensorBrick_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SensorBrick_C")
	}
	static class UBP_SensorBrick_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SensorBrick_C>();
	}
};
DUMPER7_ASSERTS_UBP_SensorBrick_C;

SDK_NAMESPACE_END
