#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ShadowBorder

#include "Basic.hpp"

#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ShadowBorder.BP_ShadowBorder_C
// 0x0000 (0x0270 - 0x0270)
class UBP_ShadowBorder_C final : public UBorder
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ShadowBorder_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ShadowBorder_C")
	}
	static class UBP_ShadowBorder_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ShadowBorder_C>();
	}
};
DUMPER7_ASSERTS_UBP_ShadowBorder_C;

SDK_NAMESPACE_END
