#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Tank_Projectile

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Tank_Projectile.BP_Tank_Projectile_C
// 0x0000 (0x0400 - 0x0400)
class ABP_Tank_Projectile_C final : public ABrickProjectile
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Tank_Projectile_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Tank_Projectile_C")
	}
	static class ABP_Tank_Projectile_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Tank_Projectile_C>();
	}
};
DUMPER7_ASSERTS_ABP_Tank_Projectile_C;

SDK_NAMESPACE_END
