#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TankBrick

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_TankBrick.BP_TankBrick_C
// 0x0000 (0x01E0 - 0x01E0)
class UBP_TankBrick_C final : public UTankBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_TankBrick_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TankBrick_C")
	}
	static class UBP_TankBrick_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_TankBrick_C>();
	}
};
DUMPER7_ASSERTS_UBP_TankBrick_C;

SDK_NAMESPACE_END
