#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ThrusterCylinder_02

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ThrusterCylinder_02.BP_ThrusterCylinder_02_C
// 0x0000 (0x0238 - 0x0238)
class UBP_ThrusterCylinder_02_C final : public UThrusterBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ThrusterCylinder_02_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ThrusterCylinder_02_C")
	}
	static class UBP_ThrusterCylinder_02_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ThrusterCylinder_02_C>();
	}
};
DUMPER7_ASSERTS_UBP_ThrusterCylinder_02_C;

SDK_NAMESPACE_END
