#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TankCylinder_02

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_TankCylinder_02.BP_TankCylinder_02_C
// 0x0000 (0x01E0 - 0x01E0)
class UBP_TankCylinder_02_C final : public UTankBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_TankCylinder_02_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TankCylinder_02_C")
	}
	static class UBP_TankCylinder_02_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_TankCylinder_02_C>();
	}
};
DUMPER7_ASSERTS_UBP_TankCylinder_02_C;

SDK_NAMESPACE_END
