#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Team_Zombies

#include "Basic.hpp"

#include "BP_Team_Default_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Team_Zombies.BP_Team_Zombies_C
// 0x0000 (0x00C8 - 0x00C8)
class UBP_Team_Zombies_C final : public UBP_Team_Default_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Team_Zombies_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Team_Zombies_C")
	}
	static class UBP_Team_Zombies_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Team_Zombies_C>();
	}
};
DUMPER7_ASSERTS_UBP_Team_Zombies_C;

SDK_NAMESPACE_END
