#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_UIFunctionLibrary

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "BrickRigs_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_UIFunctionLibrary.BP_UIFunctionLibrary_C
// 0x0000 (0x0028 - 0x0028)
class UBP_UIFunctionLibrary_C final : public UBlueprintFunctionLibrary
{
public:
	static void Get_Ammo_Type_Display_Info(EAmmoType AmmoType, class UObject* __WorldContext, int32* IconSlot, EBrickUIColorStyle* ColorStyle);
	static void UpdateHUDWidgetOpacity(class UWidget* Widget, bool bIsFocused, class UObject* __WorldContext);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_UIFunctionLibrary_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_UIFunctionLibrary_C")
	}
	static class UBP_UIFunctionLibrary_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_UIFunctionLibrary_C>();
	}
};
DUMPER7_ASSERTS_UBP_UIFunctionLibrary_C;

SDK_NAMESPACE_END
