#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_WorldSettings

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_WorldSettings.BP_WorldSettings_C
// 0x0008 (0x04B0 - 0x04A8)
class ABP_WorldSettings_C final : public ABrickWorldSettings
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x04A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_WorldSettings_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_WorldSettings_C")
	}
	static class ABP_WorldSettings_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_WorldSettings_C>();
	}
};
DUMPER7_ASSERTS_ABP_WorldSettings_C;

SDK_NAMESPACE_END
