#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Windmill

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Windmill.BP_Windmill_C
// 0x0000 (0x0268 - 0x0268)
class ABP_Windmill_C final : public AWindmill
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Windmill_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Windmill_C")
	}
	static class ABP_Windmill_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Windmill_C>();
	}
};
DUMPER7_ASSERTS_ABP_Windmill_C;

SDK_NAMESPACE_END
