#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Wagon

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Wagon.BP_Wagon_C
// 0x0000 (0x0240 - 0x0240)
class ABP_Wagon_C final : public AStaticMeshProp
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Wagon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Wagon_C")
	}
	static class ABP_Wagon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Wagon_C>();
	}
};
DUMPER7_ASSERTS_ABP_Wagon_C;

SDK_NAMESPACE_END
