#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_WindowedDoor_R_3x1x4

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_WindowedDoor_R_3x1x4.BP_WindowedDoor_R_3x1x4_C
// 0x0000 (0x0190 - 0x0190)
class UBP_WindowedDoor_R_3x1x4_C final : public UDoorBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_WindowedDoor_R_3x1x4_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_WindowedDoor_R_3x1x4_C")
	}
	static class UBP_WindowedDoor_R_3x1x4_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_WindowedDoor_R_3x1x4_C>();
	}
};
DUMPER7_ASSERTS_UBP_WindowedDoor_R_3x1x4_C;

SDK_NAMESPACE_END
