#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Wing_4x8x1s_R

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Wing_4x8x1s_R.BP_Wing_4x8x1s_R_C
// 0x0000 (0x0190 - 0x0190)
class UBP_Wing_4x8x1s_R_C final : public UWingBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Wing_4x8x1s_R_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Wing_4x8x1s_R_C")
	}
	static class UBP_Wing_4x8x1s_R_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Wing_4x8x1s_R_C>();
	}
};
DUMPER7_ASSERTS_UBP_Wing_4x8x1s_R_C;

SDK_NAMESPACE_END
