#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_WorldSetupActor

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_WorldSetupActor.BP_WorldSetupActor_C
// 0x0000 (0x0B70 - 0x0B70)
class ABP_WorldSetupActor_C final : public AWorldSetupActor
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_WorldSetupActor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_WorldSetupActor_C")
	}
	static class ABP_WorldSetupActor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_WorldSetupActor_C>();
	}
};
DUMPER7_ASSERTS_ABP_WorldSetupActor_C;

SDK_NAMESPACE_END
