#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ZombieBoss

#include "Basic.hpp"

#include "BP_Zombie_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ZombieBoss.BP_ZombieBoss_C
// 0x0000 (0x07C0 - 0x07C0)
class ABP_ZombieBoss_C final : public ABP_Zombie_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ZombieBoss_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ZombieBoss_C")
	}
	static class ABP_ZombieBoss_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ZombieBoss_C>();
	}
};
DUMPER7_ASSERTS_ABP_ZombieBoss_C;

SDK_NAMESPACE_END
