#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BT_City

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BT_City.BT_City_C
// 0x0000 (0x0228 - 0x0228)
class ABT_City_C final : public ALevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BT_City_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BT_City_C")
	}
	static class ABT_City_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABT_City_C>();
	}
};
DUMPER7_ASSERTS_ABT_City_C;

SDK_NAMESPACE_END
