#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BT_Canyon

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BT_Canyon.BT_Canyon_C
// 0x0000 (0x0228 - 0x0228)
class ABT_Canyon_C final : public ALevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BT_Canyon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BT_Canyon_C")
	}
	static class ABT_Canyon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABT_Canyon_C>();
	}
};
DUMPER7_ASSERTS_ABT_Canyon_C;

SDK_NAMESPACE_END
