#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTS_ZombieFindTarget

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AIModule_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BTS_ZombieFindTarget.BTS_ZombieFindTarget_C
// 0x0008 (0x00A0 - 0x0098)
class UBTS_ZombieFindTarget_C final : public UBTService_BlueprintBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0098(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BTS_ZombieFindTarget(int32 EntryPoint);
	void ReceiveTick(class AActor* OwnerActor, float DeltaSeconds);
	class ABrickCharacter* GetClosestCharacter(class AZombie* Zombie);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BTS_ZombieFindTarget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BTS_ZombieFindTarget_C")
	}
	static class UBTS_ZombieFindTarget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBTS_ZombieFindTarget_C>();
	}
};
DUMPER7_ASSERTS_UBTS_ZombieFindTarget_C;

SDK_NAMESPACE_END
