#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: C_Army_Digital

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass C_Army_Digital.C_Army_Digital_C
// 0x0000 (0x0050 - 0x0050)
class UC_Army_Digital_C final : public UBrickPattern
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("C_Army_Digital_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"C_Army_Digital_C")
	}
	static class UC_Army_Digital_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UC_Army_Digital_C>();
	}
};
DUMPER7_ASSERTS_UC_Army_Digital_C;

SDK_NAMESPACE_END
