#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: C_Desert

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass C_Desert.C_Desert_C
// 0x0000 (0x0050 - 0x0050)
class UC_Desert_C final : public UBrickPattern
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("C_Desert_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"C_Desert_C")
	}
	static class UC_Desert_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UC_Desert_C>();
	}
};
DUMPER7_ASSERTS_UC_Desert_C;

SDK_NAMESPACE_END
