#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: C_Heat

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass C_Heat.C_Heat_C
// 0x0000 (0x0050 - 0x0050)
class UC_Heat_C final : public UBrickPattern
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("C_Heat_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"C_Heat_C")
	}
	static class UC_Heat_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UC_Heat_C>();
	}
};
DUMPER7_ASSERTS_UC_Heat_C;

SDK_NAMESPACE_END
