#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: City2

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass City2.City2_C
// 0x0000 (0x0228 - 0x0228)
class ACity2_C final : public ALevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("City2_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"City2_C")
	}
	static class ACity2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACity2_C>();
	}
};
DUMPER7_ASSERTS_ACity2_C;

SDK_NAMESPACE_END
