#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ENiagara_SizeScaleMode

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum ENiagara_SizeScaleMode.ENiagara_SizeScaleMode
// NumValues: 0x0006
enum class ENiagara_SizeScaleMode : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator3                           = 1,
	NewEnumerator1                           = 2,
	NewEnumerator4                           = 3,
	NewEnumerator2                           = 4,
	ENiagara_MAX                             = 5,
};

SDK_NAMESPACE_END
