#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ENiagara_InfiniteLoopDuration

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum ENiagara_InfiniteLoopDuration.ENiagara_InfiniteLoopDuration
// NumValues: 0x0003
enum class ENiagara_InfiniteLoopDuration : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	ENiagara_MAX                             = 2,
};

SDK_NAMESPACE_END
