#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ENiagara_SpriteRotationMode

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum ENiagara_SpriteRotationMode.ENiagara_SpriteRotationMode
// NumValues: 0x0005
enum class ENiagara_SpriteRotationMode : uint8
{
	NewEnumerator3                           = 0,
	NewEnumerator2                           = 1,
	NewEnumerator0                           = 2,
	NewEnumerator1                           = 3,
	ENiagara_MAX                             = 4,
};

SDK_NAMESPACE_END
