#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ENiagaraEmitterScalabilityMode_Limited

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum ENiagaraEmitterScalabilityMode_Limited.ENiagaraEmitterScalabilityMode_Limited
// NumValues: 0x0003
enum class ENiagaraEmitterScalabilityMode_Limited : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	ENiagaraEmitterScalabilityMode_MAX       = 2,
};

SDK_NAMESPACE_END
