#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ENiagaraMeshTransforms

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum ENiagaraMeshTransforms.ENiagaraMeshTransforms
// NumValues: 0x0005
enum class ENiagaraMeshTransforms : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator3                           = 3,
	ENiagaraMeshTransforms_MAX               = 4,
};

SDK_NAMESPACE_END
