#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ENiagara_ScaleSpriteSize

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum ENiagara_ScaleSpriteSize.ENiagara_ScaleSpriteSize
// NumValues: 0x0005
enum class ENiagara_ScaleSpriteSize : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator3                           = 3,
	ENiagara_MAX                             = 4,
};

SDK_NAMESPACE_END
