#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Farms

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Farms.Farms_C
// 0x0000 (0x0228 - 0x0228)
class AFarms_C final : public ALevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Farms_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Farms_C")
	}
	static class AFarms_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFarms_C>();
	}
};
DUMPER7_ASSERTS_AFarms_C;

SDK_NAMESPACE_END
