#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FluUGC

#include "Basic.hpp"


SDK_NAMESPACE_START

// Enum FluUGC.EFluUGCItemVote
// NumValues: 0x0004
enum class EFluUGCItemVote : uint8
{
	None                                     = 0,
	Up                                       = 1,
	Down                                     = 2,
	EFluUGCItemVote_MAX                      = 3,
};

// Enum FluUGC.EFluUGCVisibility
// NumValues: 0x0005
enum class EFluUGCVisibility : uint8
{
	Public                                   = 0,
	FriendsOnly                              = 1,
	Private                                  = 2,
	Unlisted                                 = 3,
	EFluUGCVisibility_MAX                    = 4,
};

// ScriptStruct FluUGC.FluUGCItemIdWrapper
// 0x0010 (0x0010 - 0x0000)
struct alignas(0x08) FFluUGCItemIdWrapper final
{
public:
	uint8                                         Pad_0[0x10];                                       // 0x0000(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FFluUGCItemIdWrapper;

SDK_NAMESPACE_END
