#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GridMap

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GridMap.GridMap_C
// 0x0000 (0x0228 - 0x0228)
class AGridMap_C final : public ALevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GridMap_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GridMap_C")
	}
	static class AGridMap_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGridMap_C>();
	}
};
DUMPER7_ASSERTS_AGridMap_C;

SDK_NAMESPACE_END
