#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: P_SwirlArabica

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass P_SwirlArabica.P_SwirlArabica_C
// 0x0000 (0x0050 - 0x0050)
class UP_SwirlArabica_C final : public UBrickPattern
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("P_SwirlArabica_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"P_SwirlArabica_C")
	}
	static class UP_SwirlArabica_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UP_SwirlArabica_C>();
	}
};
DUMPER7_ASSERTS_UP_SwirlArabica_C;

SDK_NAMESPACE_END
