#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MatchMenu

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_structs.hpp"
#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_MatchMenu.WBP_MatchMenu_C
// 0x0020 (0x0298 - 0x0278)
class UWBP_MatchMenu_C final : public UMatchMenuWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0278(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_AdminLogin_C*                      WBP_AdminLogin;                                    // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMenuButtonWidget*                      RestartButton;                                     // 0x0288(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FPopupHandle                           ExitPopupHandle;                                   // 0x0290(0x0004)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)

public:
	void ExecuteUbergraph_WBP_MatchMenu(int32 EntryPoint);
	void UpdateRestartMatchButton(bool bCanRestart, bool bSameLevelAndMode);
	void UpdateCanApplyMatchSettings(bool bCanApply);
	void OnConfirmRestartPopupClosed(EPopupResult Result);
	void OnClickedRestart();
	void Construct();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_MatchMenu_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_MatchMenu_C")
	}
	static class UWBP_MatchMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MatchMenu_C>();
	}
};
DUMPER7_ASSERTS_UWBP_MatchMenu_C;

SDK_NAMESPACE_END
