#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UGCTagsProperty

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_UGCTagsProperty.WBP_UGCTagsProperty_C
// 0x0000 (0x0298 - 0x0298)
class UWBP_UGCTagsProperty_C final : public UUGCTagsPropertyWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_UGCTagsProperty_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_UGCTagsProperty_C")
	}
	static class UWBP_UGCTagsProperty_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_UGCTagsProperty_C>();
	}
};
DUMPER7_ASSERTS_UWBP_UGCTagsProperty_C;

SDK_NAMESPACE_END
