#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_InputKeySpacer

#include "Basic.hpp"

#include "BrickRigs_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_InputKeySpacer.WBP_InputKeySpacer_C.ExecuteUbergraph_WBP_InputKeySpacer
// 0x0008 (0x0008 - 0x0000)
struct WBP_InputKeySpacer_C_ExecuteUbergraph_WBP_InputKeySpacer final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBrickUIColorStyle                            K2Node_CustomEvent_NewStyle;                       // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBrickUIStyleState                            K2Node_CustomEvent_NewState;                       // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_InputKeySpacer_C_ExecuteUbergraph_WBP_InputKeySpacer;

// Function WBP_InputKeySpacer.WBP_InputKeySpacer_C.UpdateStyleState
// 0x0002 (0x0002 - 0x0000)
struct WBP_InputKeySpacer_C_UpdateStyleState final
{
public:
	EBrickUIColorStyle                            NewStyle;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBrickUIStyleState                            NewState;                                          // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_InputKeySpacer_C_UpdateStyleState;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
