#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BrickSliderReadOnly

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "WBP_BrickSlider_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_BrickSliderReadOnly.WBP_BrickSliderReadOnly_C
// 0x0008 (0x0338 - 0x0330)
class UWBP_BrickSliderReadOnly_C final : public UWBP_BrickSlider_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_WBP_BrickSliderReadOnly_C;          // 0x0330(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void PreConstruct(bool IsDesignTime_PreConstruct);
	void ExecuteUbergraph_WBP_BrickSliderReadOnly(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_BrickSliderReadOnly_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_BrickSliderReadOnly_C")
	}
	static class UWBP_BrickSliderReadOnly_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_BrickSliderReadOnly_C>();
	}
};
DUMPER7_ASSERTS_UWBP_BrickSliderReadOnly_C;

SDK_NAMESPACE_END
