#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_LoadoutContainerIcon

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_LoadoutContainerIcon.WBP_LoadoutContainerIcon_C
// 0x0000 (0x0288 - 0x0288)
class UWBP_LoadoutContainerIcon_C final : public UHUDIconWidget
{
public:
	class FText GetIconDisplayName() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_LoadoutContainerIcon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_LoadoutContainerIcon_C")
	}
	static class UWBP_LoadoutContainerIcon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_LoadoutContainerIcon_C>();
	}
};
DUMPER7_ASSERTS_UWBP_LoadoutContainerIcon_C;

SDK_NAMESPACE_END
