#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CreditsEntry

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_CreditsEntry.WBP_CreditsEntry_C.ExecuteUbergraph_WBP_CreditsEntry
// 0x0050 (0x0050 - 0x0000)
struct WBP_CreditsEntry_C_ExecuteUbergraph_WBP_CreditsEntry final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetLicenseFileContent_ReturnValue;        // 0x0008(0x0018)()
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UExpandableArea*                        K2Node_ComponentBoundEvent_Area;                   // 0x0028(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bIsExpanded;            // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0038(0x0018)()
};
DUMPER7_ASSERTS_WBP_CreditsEntry_C_ExecuteUbergraph_WBP_CreditsEntry;

// Function WBP_CreditsEntry.WBP_CreditsEntry_C.BndEvt__WBP_CreditsEntry_ExpandableArea_K2Node_ComponentBoundEvent_0_OnExpandableAreaExpansionChanged__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct WBP_CreditsEntry_C_BndEvt__WBP_CreditsEntry_ExpandableArea_K2Node_ComponentBoundEvent_0_OnExpandableAreaExpansionChanged__DelegateSignature final
{
public:
	class UExpandableArea*                        Area;                                              // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsExpanded;                                       // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WBP_CreditsEntry_C_BndEvt__WBP_CreditsEntry_ExpandableArea_K2Node_ComponentBoundEvent_0_OnExpandableAreaExpansionChanged__DelegateSignature;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
