#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_AdminLogin

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_AdminLogin.WBP_AdminLogin_C
// 0x0000 (0x0298 - 0x0298)
class UWBP_AdminLogin_C final : public UAdminLoginWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_AdminLogin_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_AdminLogin_C")
	}
	static class UWBP_AdminLogin_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_AdminLogin_C>();
	}
};
DUMPER7_ASSERTS_UWBP_AdminLogin_C;

SDK_NAMESPACE_END
