#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BrickButton

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_BrickButton.WBP_BrickButton_C
// 0x0000 (0x0310 - 0x0310)
class UWBP_BrickButton_C final : public UBrickButtonWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_BrickButton_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_BrickButton_C")
	}
	static class UWBP_BrickButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_BrickButton_C>();
	}
};
DUMPER7_ASSERTS_UWBP_BrickButton_C;

SDK_NAMESPACE_END
