#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ServerBrowser

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_ServerBrowser.WBP_ServerBrowser_C
// 0x0018 (0x02C0 - 0x02A8)
class UWBP_ServerBrowser_C final : public UServerBrowserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UMenuButtonWidget*                      RefreshButton;                                     // 0x02B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMenuButtonWidget*                      JoinButton;                                        // 0x02B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_ServerBrowser(int32 EntryPoint);
	void UpdateCanJoin(bool bCanJoin);
	void UpdateCanRefresh(bool bCanRefresh);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_ServerBrowser_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_ServerBrowser_C")
	}
	static class UWBP_ServerBrowser_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ServerBrowser_C>();
	}
};
DUMPER7_ASSERTS_UWBP_ServerBrowser_C;

SDK_NAMESPACE_END
