#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_InputChord

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_structs.hpp"
#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_InputChord.WBP_InputChord_C
// 0x0010 (0x02D0 - 0x02C0)
class UWBP_InputChord_C final : public UInputChordWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBrickHorizontalBox*                    KeysBox;                                           // 0x02C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_InputChord(int32 EntryPoint);
	void UpdateSpacerColorStyleAndStyleState(class UUserWidget* Widget, EBrickUIColorStyle NewColorStyle, EBrickUIStyleState NewStyleState);
	void AddSpacerWidget(class UUserWidget* Widget);
	void AddKeyWidget(class UInputKeyWidget* Widget);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_InputChord_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_InputChord_C")
	}
	static class UWBP_InputChord_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_InputChord_C>();
	}
};
DUMPER7_ASSERTS_UWBP_InputChord_C;

SDK_NAMESPACE_END
