#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UserInterfaceSettings

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_UserInterfaceSettings.WBP_UserInterfaceSettings_C
// 0x0000 (0x0298 - 0x0298)
class UWBP_UserInterfaceSettings_C final : public UMenuSettingsPageWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_UserInterfaceSettings_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_UserInterfaceSettings_C")
	}
	static class UWBP_UserInterfaceSettings_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_UserInterfaceSettings_C>();
	}
};
DUMPER7_ASSERTS_UWBP_UserInterfaceSettings_C;

SDK_NAMESPACE_END
