#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UGCTaskPopup

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_structs.hpp"
#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_UGCTaskPopup.WBP_UGCTaskPopup_C
// 0x0018 (0x02E0 - 0x02C8)
class UWBP_UGCTaskPopup_C final : public UUGCTaskPopupWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_BrickSliderReadOnly_C*             Slider;                                            // 0x02D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMenuButtonWidget*                      ConfirmButton;                                     // 0x02D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_UGCTaskPopup(int32 EntryPoint);
	void UpdateIsFinished(bool bNewFinished, bool bNewSuccess);
	void Construct();
	void UpdateProgress(float NewProgress);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_UGCTaskPopup_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_UGCTaskPopup_C")
	}
	static class UWBP_UGCTaskPopup_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_UGCTaskPopup_C>();
	}
};
DUMPER7_ASSERTS_UWBP_UGCTaskPopup_C;

SDK_NAMESPACE_END
