#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Dashboard

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_Dashboard.WBP_Dashboard_C
// 0x0018 (0x02D0 - 0x02B8)
class UWBP_Dashboard_C final : public UDashboardWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBrickHorizontalBox*                    IconsBox;                                          // 0x02C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBrickGridPanel*                        SlidersPanel;                                      // 0x02C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_Dashboard(int32 EntryPoint);
	void UpdateSliderWidgetSlot(class UDashboardSliderWidget* Widget, int32 Index_0, int32 NumSliders);
	void AddIconWidget(class UDashboardIconWidget* Widget, int32 Index_0);
	void AddSliderWidget(class UDashboardSliderWidget* Widget);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Dashboard_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Dashboard_C")
	}
	static class UWBP_Dashboard_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Dashboard_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Dashboard_C;

SDK_NAMESPACE_END
