#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Menu

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_structs.hpp"
#include "BrickRigs_classes.hpp"
#include "GameLogoEnum_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_Menu.WBP_Menu_C
// 0x0030 (0x0320 - 0x02F0)
class UWBP_Menu_C final : public UMenuWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_GameLogo_C*                        Logo;                                              // 0x02F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBrickBorder*                           MenuPageBorder;                                    // 0x0300(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_PropertiesPanel_C*                 TopPropertiesPanel;                                // 0x0308(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBrickTextBlock*                        VersionTextBlock;                                  // 0x0310(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FPopupHandle                           PopupHandle;                                       // 0x0318(0x0004)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)

public:
	void ExecuteUbergraph_WBP_Menu(int32 EntryPoint);
	void Construct();
	void OnInitialized();
	void RemoveMenuPage(class UMenuPageWidget* Widget);
	void OnClickedQuickGame();
	void OnClosedMainMenuPopup(EPopupResult Result);
	void OnClickedMainMenu();
	void OnClickedEditorSettings();
	void OnClickedInputMappings();
	void OnClickedPlayersMenu();
	void OnClickedAdminSettings();
	void OnClickedMatchMenu();
	void OnClosedQuitGamePopup(EPopupResult Result);
	void OnClickedUISettings();
	void OnClickedCredits();
	void OnClickedInputSettings();
	void OnClickedVideoSettings();
	void OnClickedGameplaySettings();
	void OnClickedJoinGame();
	void OnClickedHostGame();
	void OnClickedOptions();
	void AddMenuPage(class UMenuPageWidget* Widget);
	void OnMenuContextChanged(const class FName& NewContext);
	void CreateBackButton();
	void CreateAdminMenuButton();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Menu_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Menu_C")
	}
	static class UWBP_Menu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Menu_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Menu_C;

SDK_NAMESPACE_END
