#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PropertiesPanel

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_PropertiesPanel.WBP_PropertiesPanel_C
// 0x0010 (0x02E0 - 0x02D0)
class UWBP_PropertiesPanel_C final : public UPropertiesPanelWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBrickVerticalBox*                      MainBox;                                           // 0x02D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_PropertiesPanel(int32 EntryPoint);
	void AddCategoryWidget(class UPropertyCategoryWidget* Widget, int32 Index_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_PropertiesPanel_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_PropertiesPanel_C")
	}
	static class UWBP_PropertiesPanel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_PropertiesPanel_C>();
	}
};
DUMPER7_ASSERTS_UWBP_PropertiesPanel_C;

SDK_NAMESPACE_END
