#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BrickComboBoxItemContainer

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_BrickComboBoxItemContainer.WBP_BrickComboBoxItemContainer_C.ExecuteUbergraph_WBP_BrickComboBoxItemContainer
// 0x0018 (0x0018 - 0x0000)
struct WBP_BrickComboBoxItemContainer_C_ExecuteUbergraph_WBP_BrickComboBoxItemContainer final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UBrickComboBoxItemWidget*               K2Node_Event_Widget;                               // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bNewSelected;                         // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WBP_BrickComboBoxItemContainer_C_ExecuteUbergraph_WBP_BrickComboBoxItemContainer;

// Function WBP_BrickComboBoxItemContainer.WBP_BrickComboBoxItemContainer_C.UpdateIsSelected
// 0x0001 (0x0001 - 0x0000)
struct WBP_BrickComboBoxItemContainer_C_UpdateIsSelected final
{
public:
	bool                                          bNewSelected;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WBP_BrickComboBoxItemContainer_C_UpdateIsSelected;

// Function WBP_BrickComboBoxItemContainer.WBP_BrickComboBoxItemContainer_C.AddItemWidget
// 0x0008 (0x0008 - 0x0000)
struct WBP_BrickComboBoxItemContainer_C_AddItemWidget final
{
public:
	class UBrickComboBoxItemWidget*               Widget;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_BrickComboBoxItemContainer_C_AddItemWidget;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
