#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ScoreboardPopup

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_ScoreboardPopup.WBP_ScoreboardPopup_C
// 0x0010 (0x02A8 - 0x0298)
class UWBP_ScoreboardPopup_C final : public UScoreboardPopupWidget
{
public:
	class UWBP_MatchTimer_C*                      WBP_MatchTimer;                                    // 0x0298(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Scoreboard_C*                      WBP_Scoreboard;                                    // 0x02A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_ScoreboardPopup_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_ScoreboardPopup_C")
	}
	static class UWBP_ScoreboardPopup_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ScoreboardPopup_C>();
	}
};
DUMPER7_ASSERTS_UWBP_ScoreboardPopup_C;

SDK_NAMESPACE_END
