#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_GameLogo

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameLogoEnum_structs.hpp"
#include "BrickRigs_structs.hpp"
#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_GameLogo.WBP_GameLogo_C
// 0x0028 (0x0288 - 0x0260)
class UWBP_GameLogo_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBrickBorder*                           Border;                                            // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBrickImage*                            LogoImage;                                         // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	EGameLogoEnum                                 Logo;                                              // 0x0278(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_279[0x7];                                      // 0x0279(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBrickUIStyle*                          UIStyle;                                           // 0x0280(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_GameLogo(int32 EntryPoint);
	void UpdateUIStyle(const class UBrickUIStyle* Style);
	void Construct();
	void UpdateLogo();
	void SetLogo(EGameLogoEnum InLogo);
	class UMaterialInstanceDynamic* InitMID();

	bool IsLogoReady() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_GameLogo_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_GameLogo_C")
	}
	static class UWBP_GameLogo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_GameLogo_C>();
	}
};
DUMPER7_ASSERTS_UWBP_GameLogo_C;

SDK_NAMESPACE_END
