#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_LoadingScreen

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_LoadingScreen.WBP_LoadingScreen_C
// 0x0028 (0x02A0 - 0x0278)
class UWBP_LoadingScreen_C final : public ULoadingScreenWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0278(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBorder*                                BackgroundBorder;                                  // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBrickImage*                            BrickImage_123;                                    // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_GameLogo_C*                        GameLogo;                                          // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBrickTextBlock*                        LoadingTextBlock;                                  // 0x0298(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_LoadingScreen(int32 EntryPoint);
	void SetLoadingText(const class FText& Text);
	void SetBackgroundColor(const struct FLinearColor& InColor);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_LoadingScreen_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_LoadingScreen_C")
	}
	static class UWBP_LoadingScreen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_LoadingScreen_C>();
	}
};
DUMPER7_ASSERTS_UWBP_LoadingScreen_C;

SDK_NAMESPACE_END
