#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_NumericProperty

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_structs.hpp"
#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_NumericProperty.WBP_NumericProperty_C
// 0x0018 (0x02C8 - 0x02B0)
class UWBP_NumericProperty_C final : public UNumericPropertyWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBrickHorizontalBox*                    SlidersBox;                                        // 0x02B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMenuButtonWidget*                      LockButton;                                        // 0x02C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_NumericProperty(int32 EntryPoint);
	void Destruct();
	void OnLockButtonClicked();
	void UpdateNumericProperty(const ENumericValueType ValueType, const int32 NumAxes);
	void OnBrickUnitsButtonClicked();
	void AddSliderWidget(class UBrickSliderWidget* Slider);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_NumericProperty_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_NumericProperty_C")
	}
	static class UWBP_NumericProperty_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_NumericProperty_C>();
	}
};
DUMPER7_ASSERTS_UWBP_NumericProperty_C;

SDK_NAMESPACE_END
