#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TeamScore

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_structs.hpp"
#include "BrickRigs_classes.hpp"
#include "AIModule_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_TeamScore.WBP_TeamScore_C
// 0x0020 (0x0298 - 0x0278)
class UWBP_TeamScore_C final : public UTeamScoreWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0278(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBrickBorder*                           Border;                                            // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBrickImage*                            IconImage;                                         // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBrickTextBlock*                        ScoreTextBlock;                                    // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void UpdateScore(int32 NewScore_UpdateScore, int32 NewMaxScore_UpdateScore);
	void UpdateTeamAttitude(ETeamAttitude NewTeamAttitude_UpdateTeamAttitude);
	void UpdateTeamIcon(class UTexture2D* NewIcon_UpdateTeamIcon);
	void ExecuteUbergraph_WBP_TeamScore(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_TeamScore_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_TeamScore_C")
	}
	static class UWBP_TeamScore_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_TeamScore_C>();
	}
};
DUMPER7_ASSERTS_UWBP_TeamScore_C;

SDK_NAMESPACE_END
