#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_AdminMenu

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_AdminMenu.WBP_AdminMenu_C
// 0x0028 (0x02E0 - 0x02B8)
class UWBP_AdminMenu_C final : public UAdminMenuWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_AdminLogin_C*                      AdminLoginWidget;                                  // 0x02C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMenuButtonWidget*                      ShowProfileButton;                                 // 0x02C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMenuButtonWidget*                      EditKickButton;                                    // 0x02D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMenuButtonWidget*                      KickPlayerByIDButton;                              // 0x02D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_AdminMenu(int32 EntryPoint);
	void UpdateCanViewAndEditKicks(bool bNewCanViewAndEdit);
	void UpdateHasSelectedKick(bool bNewSelected);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_AdminMenu_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_AdminMenu_C")
	}
	static class UWBP_AdminMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_AdminMenu_C>();
	}
};
DUMPER7_ASSERTS_UWBP_AdminMenu_C;

SDK_NAMESPACE_END
