#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_GameplaySettings

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_GameplaySettings.WBP_GameplaySettings_C
// 0x0000 (0x0298 - 0x0298)
class UWBP_GameplaySettings_C final : public UMenuSettingsPageWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_GameplaySettings_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_GameplaySettings_C")
	}
	static class UWBP_GameplaySettings_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_GameplaySettings_C>();
	}
};
DUMPER7_ASSERTS_UWBP_GameplaySettings_C;

SDK_NAMESPACE_END
