#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MapCrosshair

#include "Basic.hpp"

#include "BrickRigs_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_MapCrosshair.WBP_MapCrosshair_C.ExecuteUbergraph_WBP_MapCrosshair
// 0x0008 (0x0008 - 0x0000)
struct WBP_MapCrosshair_C_ExecuteUbergraph_WBP_MapCrosshair final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBrickUIColorStyle                            K2Node_Event_NewStyle;                             // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBrickUIStyleState                            K2Node_Event_NewState;                             // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_MapCrosshair_C_ExecuteUbergraph_WBP_MapCrosshair;

// Function WBP_MapCrosshair.WBP_MapCrosshair_C.SetStyleState
// 0x0001 (0x0001 - 0x0000)
struct WBP_MapCrosshair_C_SetStyleState final
{
public:
	EBrickUIStyleState                            NewState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_MapCrosshair_C_SetStyleState;

// Function WBP_MapCrosshair.WBP_MapCrosshair_C.SetColorStyle
// 0x0001 (0x0001 - 0x0000)
struct WBP_MapCrosshair_C_SetColorStyle final
{
public:
	EBrickUIColorStyle                            NewStyle;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_MapCrosshair_C_SetColorStyle;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
