#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PingIndicator

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_PingIndicator.WBP_PingIndicator_C
// 0x0010 (0x0290 - 0x0280)
class UWBP_PingIndicator_C final : public UPingIndicatorWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0280(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBrickImage*                            ConnectionImage;                                   // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_PingIndicator(int32 EntryPoint);
	void UpdatePing(int32 InPing);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_PingIndicator_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_PingIndicator_C")
	}
	static class UWBP_PingIndicator_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_PingIndicator_C>();
	}
};
DUMPER7_ASSERTS_UWBP_PingIndicator_C;

SDK_NAMESPACE_END
