#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ScoreboardTeam

#include "Basic.hpp"

#include "AIModule_structs.hpp"
#include "UMG_structs.hpp"
#include "BrickRigs_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_ScoreboardTeam.WBP_ScoreboardTeam_C.ExecuteUbergraph_WBP_ScoreboardTeam
// 0x0014 (0x0014 - 0x0000)
struct WBP_ScoreboardTeam_C_ExecuteUbergraph_WBP_ScoreboardTeam final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EBrickUIColorStyle                            Temp_byte_Variable_2;                              // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bIsOwnTeam;                           // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ETeamAttitude                                 K2Node_Event_NewAttitude;                          // 0x000A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBrickUIColorStyle                            CallFunc_GetTeamAttitudeColorStyle_ReturnValue;    // 0x000B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBrickUIColorStyle                            K2Node_Select_Default;                             // 0x000C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bCanJoin_1;                           // 0x000D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select_Default_1;                           // 0x000E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bCanJoin;                             // 0x000F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EBrickUIColorStyle                            K2Node_ComponentBoundEvent_InColorStyle;           // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBrickUIStyleState                            K2Node_ComponentBoundEvent_InContentStyleState;    // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_ScoreboardTeam_C_ExecuteUbergraph_WBP_ScoreboardTeam;

// Function WBP_ScoreboardTeam.WBP_ScoreboardTeam_C.BndEvt__JoinButton_K2Node_ComponentBoundEvent_1_OnUpdateContentStyle__DelegateSignature
// 0x0002 (0x0002 - 0x0000)
struct WBP_ScoreboardTeam_C_BndEvt__JoinButton_K2Node_ComponentBoundEvent_1_OnUpdateContentStyle__DelegateSignature final
{
public:
	EBrickUIColorStyle                            InColorStyle;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBrickUIStyleState                            InContentStyleState;                               // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_ScoreboardTeam_C_BndEvt__JoinButton_K2Node_ComponentBoundEvent_1_OnUpdateContentStyle__DelegateSignature;

// Function WBP_ScoreboardTeam.WBP_ScoreboardTeam_C.UpdateCanJoinTeam
// 0x0001 (0x0001 - 0x0000)
struct WBP_ScoreboardTeam_C_UpdateCanJoinTeam final
{
public:
	bool                                          bCanJoin;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WBP_ScoreboardTeam_C_UpdateCanJoinTeam;

// Function WBP_ScoreboardTeam.WBP_ScoreboardTeam_C.UpdateCanEverJoinTeam
// 0x0001 (0x0001 - 0x0000)
struct WBP_ScoreboardTeam_C_UpdateCanEverJoinTeam final
{
public:
	bool                                          bCanJoin;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WBP_ScoreboardTeam_C_UpdateCanEverJoinTeam;

// Function WBP_ScoreboardTeam.WBP_ScoreboardTeam_C.UpdateTeamAttitude
// 0x0002 (0x0002 - 0x0000)
struct WBP_ScoreboardTeam_C_UpdateTeamAttitude final
{
public:
	bool                                          bIsOwnTeam;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	ETeamAttitude                                 NewAttitude;                                       // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_ScoreboardTeam_C_UpdateTeamAttitude;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
