#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MatchState

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_structs.hpp"
#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_MatchState.WBP_MatchState_C
// 0x0020 (0x0298 - 0x0278)
class UWBP_MatchState_C final : public UMatchStateWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0278(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       FadeAnimation;                                     // 0x0280(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UBrickBorder*                           Border;                                            // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBrickTextBlock*                        TextBlock;                                         // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void UpdateMatchState(const class FText& NewDisplayText_UpdateMatchState, EBrickUIColorStyle NewColorStyle_UpdateMatchState, bool bFadeOut_UpdateMatchState);
	void OnAnimationFinished(const class UWidgetAnimation* Animation_OnAnimationFinished);
	void ExecuteUbergraph_WBP_MatchState(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_MatchState_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_MatchState_C")
	}
	static class UWBP_MatchState_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MatchState_C>();
	}
};
DUMPER7_ASSERTS_UWBP_MatchState_C;

SDK_NAMESPACE_END
