#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BrickComboBox

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "BrickRigs_structs.hpp"
#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_BrickComboBox.WBP_BrickComboBox_C
// 0x0018 (0x0308 - 0x02F0)
class UWBP_BrickComboBox_C final : public UBrickComboBoxWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBrickImage*                            ArrowImage;                                        // 0x02F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UGridPanel*                             ButtonPanel;                                       // 0x0300(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_BrickComboBox(int32 EntryPoint);
	void UpdateUseItemList(bool bInUseItemList);
	void AddSelectedItemWidget(class UBrickComboBoxItemWidget* Widget);
	void BndEvt__Button_K2Node_ComponentBoundEvent_1_OnUpdateContentStyle__DelegateSignature(EBrickUIColorStyle InColorStyle, EBrickUIStyleState InContentStyleState);
	void BndEvt__Button_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_BrickComboBox_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_BrickComboBox_C")
	}
	static class UWBP_BrickComboBox_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_BrickComboBox_C>();
	}
};
DUMPER7_ASSERTS_UWBP_BrickComboBox_C;

SDK_NAMESPACE_END
