#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BindKeyPopup

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "BrickRigs_structs.hpp"
#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_BindKeyPopup.WBP_BindKeyPopup_C
// 0x0020 (0x0348 - 0x0328)
class UWBP_BindKeyPopup_C final : public UBindKeyPopupWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0328(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBrickBorder*                           ConflictsBorder;                                   // 0x0330(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBrickTextBlock*                        ConflictsTextBlock;                                // 0x0338(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBrickBorder*                           ControlHintBorder;                                 // 0x0340(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_BindKeyPopup(int32 EntryPoint);
	void UpdateIsBindingKey(bool bNewIsBinding);
	void PreConstruct(bool IsDesignTime);
	void UpdateConflictedMappings(bool bIsConflicted, const TArray<class FText>& ConflictedMappingNames);
	void Construct();

	class FText ConflictsArrayToText(class FText& InText, TArray<class FText>& InConflictNames) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_BindKeyPopup_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_BindKeyPopup_C")
	}
	static class UWBP_BindKeyPopup_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_BindKeyPopup_C>();
	}
};
DUMPER7_ASSERTS_UWBP_BindKeyPopup_C;

SDK_NAMESPACE_END
