#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SpawnPointPanel

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_SpawnPointPanel.WBP_SpawnPointPanel_C
// 0x0000 (0x0308 - 0x0308)
class UWBP_SpawnPointPanel_C final : public USpawnPointPanelWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_SpawnPointPanel_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_SpawnPointPanel_C")
	}
	static class UWBP_SpawnPointPanel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_SpawnPointPanel_C>();
	}
};
DUMPER7_ASSERTS_UWBP_SpawnPointPanel_C;

SDK_NAMESPACE_END
