#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MapCrosshair

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_structs.hpp"
#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_MapCrosshair.WBP_MapCrosshair_C
// 0x0018 (0x0278 - 0x0260)
class UWBP_MapCrosshair_C final : public UMapCrosshairWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBrickImage*                            ArrowHeadImage;                                    // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBrickImage*                            LineImage;                                         // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_MapCrosshair(int32 EntryPoint);
	void SetStyleState(EBrickUIStyleState NewState);
	void SetColorStyle(EBrickUIColorStyle NewStyle);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_MapCrosshair_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_MapCrosshair_C")
	}
	static class UWBP_MapCrosshair_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MapCrosshair_C>();
	}
};
DUMPER7_ASSERTS_UWBP_MapCrosshair_C;

SDK_NAMESPACE_END
