#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BrickComboBoxItem

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_BrickComboBoxItem.WBP_BrickComboBoxItem_C.ExecuteUbergraph_WBP_BrickComboBoxItem
// 0x0004 (0x0004 - 0x0000)
struct WBP_BrickComboBoxItem_C_ExecuteUbergraph_WBP_BrickComboBoxItem final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_BrickComboBoxItem_C_ExecuteUbergraph_WBP_BrickComboBoxItem;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
