#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_DashboardSlider

#include "Basic.hpp"

#include "BrickRigs_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_DashboardSlider.WBP_DashboardSlider_C.ExecuteUbergraph_WBP_DashboardSlider
// 0x0014 (0x0014 - 0x0000)
struct WBP_DashboardSlider_C_ExecuteUbergraph_WBP_DashboardSlider final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_Event_IconIndex;                            // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FBrickUIIconSlot                       K2Node_MakeStruct_BrickUIIconSlot;                 // 0x0008(0x0008)(NoDestructor)
	EBrickUIColorStyle                            K2Node_Event_NewStyle;                             // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_DashboardSlider_C_ExecuteUbergraph_WBP_DashboardSlider;

// Function WBP_DashboardSlider.WBP_DashboardSlider_C.UpdateColorStyle
// 0x0001 (0x0001 - 0x0000)
struct WBP_DashboardSlider_C_UpdateColorStyle final
{
public:
	EBrickUIColorStyle                            NewStyle;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_DashboardSlider_C_UpdateColorStyle;

// Function WBP_DashboardSlider.WBP_DashboardSlider_C.UpdateIcon
// 0x0004 (0x0004 - 0x0000)
struct WBP_DashboardSlider_C_UpdateIcon final
{
public:
	int32                                         IconIndex;                                         // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_DashboardSlider_C_UpdateIcon;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
