#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ServerBrowser

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_ServerBrowser.WBP_ServerBrowser_C.ExecuteUbergraph_WBP_ServerBrowser
// 0x0048 (0x0048 - 0x0000)
struct WBP_ServerBrowser_C_ExecuteUbergraph_WBP_ServerBrowser final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMenuWidget*                            CallFunc_GetMenuWidget_ReturnValue;                // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0010(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0020(0x0010)(ZeroConstructor, NoDestructor)
	class UMenuButtonWidget*                      CallFunc_CreateRefreshButton_ReturnValue;          // 0x0030(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMenuButtonWidget*                      CallFunc_CreateButton_ReturnValue;                 // 0x0038(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bCanRefresh;                          // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_bCanJoin;                             // 0x0041(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WBP_ServerBrowser_C_ExecuteUbergraph_WBP_ServerBrowser;

// Function WBP_ServerBrowser.WBP_ServerBrowser_C.UpdateCanJoin
// 0x0001 (0x0001 - 0x0000)
struct WBP_ServerBrowser_C_UpdateCanJoin final
{
public:
	bool                                          bCanJoin;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WBP_ServerBrowser_C_UpdateCanJoin;

// Function WBP_ServerBrowser.WBP_ServerBrowser_C.UpdateCanRefresh
// 0x0001 (0x0001 - 0x0000)
struct WBP_ServerBrowser_C_UpdateCanRefresh final
{
public:
	bool                                          bCanRefresh;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WBP_ServerBrowser_C_UpdateCanRefresh;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
