#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CapturePointIcon

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_CapturePointIcon.WBP_CapturePointIcon_C
// 0x0000 (0x02C8 - 0x02C8)
class UWBP_CapturePointIcon_C final : public UCapturePointIconWidget
{
public:
	class FText GetIconDisplayName() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_CapturePointIcon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_CapturePointIcon_C")
	}
	static class UWBP_CapturePointIcon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CapturePointIcon_C>();
	}
};
DUMPER7_ASSERTS_UWBP_CapturePointIcon_C;

SDK_NAMESPACE_END
