#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CrosshairArrow

#include "Basic.hpp"

#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_CrosshairArrow.WBP_CrosshairArrow_C
// 0x0008 (0x0268 - 0x0260)
class UWBP_CrosshairArrow_C final : public UUserWidget
{
public:
	class UBrickImage*                            BrickImage_36;                                     // 0x0260(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_CrosshairArrow_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_CrosshairArrow_C")
	}
	static class UWBP_CrosshairArrow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CrosshairArrow_C>();
	}
};
DUMPER7_ASSERTS_UWBP_CrosshairArrow_C;

SDK_NAMESPACE_END
