#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_HurtMarker

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_HurtMarker.WBP_HurtMarker_C
// 0x0018 (0x0288 - 0x0270)
class UWBP_HurtMarker_C final : public UHurtMarkerWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0270(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       HurtMarkerAnim;                                    // 0x0278(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UBrickImage*                            BrickImage_77;                                     // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_HurtMarker(int32 EntryPoint);
	void PlayHurtMarkerAnimation();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_HurtMarker_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_HurtMarker_C")
	}
	static class UWBP_HurtMarker_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_HurtMarker_C>();
	}
};
DUMPER7_ASSERTS_UWBP_HurtMarker_C;

SDK_NAMESPACE_END
