#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BrickComboBoxItemContainer

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_BrickComboBoxItemContainer.WBP_BrickComboBoxItemContainer_C
// 0x0008 (0x0298 - 0x0290)
class UWBP_BrickComboBoxItemContainer_C final : public UBrickComboBoxItemContainerWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0290(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_WBP_BrickComboBoxItemContainer(int32 EntryPoint);
	void BndEvt__Button_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature();
	void UpdateIsSelected(bool bNewSelected);
	void AddItemWidget(class UBrickComboBoxItemWidget* Widget);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_BrickComboBoxItemContainer_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_BrickComboBoxItemContainer_C")
	}
	static class UWBP_BrickComboBoxItemContainer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_BrickComboBoxItemContainer_C>();
	}
};
DUMPER7_ASSERTS_UWBP_BrickComboBoxItemContainer_C;

SDK_NAMESPACE_END
