#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_InputActionCategory

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_structs.hpp"
#include "BrickRigs_classes.hpp"
#include "SlateCore_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_InputActionCategory.WBP_InputActionCategory_C
// 0x0018 (0x0298 - 0x0280)
class UWBP_InputActionCategory_C final : public UInputActionCategoryWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0280(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_BrickButton_C*                     Button;                                            // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBrickTextBlock*                        TextBlock;                                         // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_InputActionCategory(int32 EntryPoint);
	void UpdateInputActionListMode(EInputActionListMode NewMode);
	void UpdateIsSelected(bool bNewSelected);
	void InitializeCategory(const class FText& InCategoryName);
	void BndEvt__Button_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature();
	void BndEvt__Button_K2Node_ComponentBoundEvent_0_OnUpdateContentStyle__DelegateSignature(EBrickUIColorStyle InColorStyle, EBrickUIStyleState InContentStyleState);

	class UWidget* GetWidgetToFocus() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_InputActionCategory_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_InputActionCategory_C")
	}
	static class UWBP_InputActionCategory_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_InputActionCategory_C>();
	}
};
DUMPER7_ASSERTS_UWBP_InputActionCategory_C;

SDK_NAMESPACE_END
