#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UserIdProperty

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_structs.hpp"
#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_UserIdProperty.WBP_UserIdProperty_C
// 0x0020 (0x0310 - 0x02F0)
class UWBP_UserIdProperty_C final : public UUserIdPropertyWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_BrickButton_C*                     ShowProfileButton;                                 // 0x02F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBrickImage*                            ShowProfileImage;                                  // 0x0300(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBrickTextBlock*                        UsernameTextBlock;                                 // 0x0308(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_UserIdProperty(int32 EntryPoint);
	void UpdateIsReadOnly(bool bNewReadOnly);
	void UpdateUserId(const class FText& InUserId, const bool bIsValid);
	void BndEvt__ShowProfileButton_K2Node_ComponentBoundEvent_1_OnUpdateContentStyle__DelegateSignature(EBrickUIColorStyle InColorStyle, EBrickUIStyleState InContentStyleState);
	void BndEvt__ShowProfileButton_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature();
	void UpdateUsername(const class FText& InUsername);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_UserIdProperty_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_UserIdProperty_C")
	}
	static class UWBP_UserIdProperty_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_UserIdProperty_C>();
	}
};
DUMPER7_ASSERTS_UWBP_UserIdProperty_C;

SDK_NAMESPACE_END
