#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MatchEnd

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_structs.hpp"
#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_MatchEnd.WBP_MatchEnd_C
// 0x0020 (0x0288 - 0x0268)
class UWBP_MatchEnd_C final : public UMatchEndWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0268(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_MenuButtonPanel_C*                 ButtonPanel;                                       // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMenuButtonWidget*                      ContinueButton;                                    // 0x0278(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FPopupHandle                           LeavePopupHandle;                                  // 0x0280(0x0004)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)

public:
	void ExecuteUbergraph_WBP_MatchEnd(int32 EntryPoint);
	void OnClosedExitMatchPopup(EPopupResult Result);
	void OnClickedExit();
	void Construct();
	void UpdateContinueButton(int32 TimeRemaining, bool bIsHost);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_MatchEnd_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_MatchEnd_C")
	}
	static class UWBP_MatchEnd_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MatchEnd_C>();
	}
};
DUMPER7_ASSERTS_UWBP_MatchEnd_C;

SDK_NAMESPACE_END
