#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Interaction

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_Interaction.WBP_Interaction_C
// 0x0010 (0x0298 - 0x0288)
class UWBP_Interaction_C final : public UInteractionWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0288(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBrickVerticalBox*                      OptionsBox;                                        // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void AddOptionWidget(class UInteractionOptionWidget* Widget_AddOptionWidget, int32 OptionIndex_AddOptionWidget);
	void ExecuteUbergraph_WBP_Interaction(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Interaction_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Interaction_C")
	}
	static class UWBP_Interaction_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Interaction_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Interaction_C;

SDK_NAMESPACE_END
