#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UnsavedChangesPopup

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_UnsavedChangesPopup.WBP_UnsavedChangesPopup_C
// 0x0008 (0x02A0 - 0x0298)
class UWBP_UnsavedChangesPopup_C final : public UUnsavedChangesPopupWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0298(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_WBP_UnsavedChangesPopup(int32 EntryPoint);
	void SaveChanges();
	void DiscardChanges();
	void Construct();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_UnsavedChangesPopup_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_UnsavedChangesPopup_C")
	}
	static class UWBP_UnsavedChangesPopup_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_UnsavedChangesPopup_C>();
	}
};
DUMPER7_ASSERTS_UWBP_UnsavedChangesPopup_C;

SDK_NAMESPACE_END
