#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Scoreboard

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_Scoreboard.WBP_Scoreboard_C
// 0x0010 (0x02F8 - 0x02E8)
class UWBP_Scoreboard_C final : public UScoreboardWidget
{
public:
	class UMenuButtonWidget*                      PlayerProfileButton;                               // 0x02E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMenuButtonWidget*                      KickButton;                                        // 0x02F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Scoreboard_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Scoreboard_C")
	}
	static class UWBP_Scoreboard_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Scoreboard_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Scoreboard_C;

SDK_NAMESPACE_END
