#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_HUDIconContainer

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_HUDIconContainer.WBP_HUDIconContainer_C
// 0x0010 (0x02E0 - 0x02D0)
class UWBP_HUDIconContainer_C final : public UHUDIconContainerWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBrickGridPanel*                        GridPanel;                                         // 0x02D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_HUDIconContainer(int32 EntryPoint);
	void AddCrosshairWidgets(const TArray<class UMapCrosshairWidget*>& Widgets);
	void AddInteractionWidget(class UInteractionWidget* Widget);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_HUDIconContainer_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_HUDIconContainer_C")
	}
	static class UWBP_HUDIconContainer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_HUDIconContainer_C>();
	}
};
DUMPER7_ASSERTS_UWBP_HUDIconContainer_C;

SDK_NAMESPACE_END
