#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BrickEditorObjectProperty

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "BrickRigs_structs.hpp"
#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_BrickEditorObjectProperty.WBP_BrickEditorObjectProperty_C
// 0x0038 (0x02B8 - 0x0280)
class UWBP_BrickEditorObjectProperty_C final : public UBrickEditorObjectPropertyWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0280(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_BrickButton_C*                     ClearButton;                                       // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBrickImage*                            ClearImage;                                        // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBrickTextBlock*                        ObjectsTextBlock;                                  // 0x0298(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_BrickButton_C*                     PickObjectsButton;                                 // 0x02A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_BrickButton_C*                     SelectButton;                                      // 0x02A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBrickImage*                            SelectImage;                                       // 0x02B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_BrickEditorObjectProperty(int32 EntryPoint);
	void UpdateIsReadOnly(bool bNewReadOnly);
	void BndEvt__WBP_BrickEditorObjectProperty_SelectButton_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature();
	void BndEvt__WBP_BrickEditorObjectProperty_SelectButton_K2Node_ComponentBoundEvent_2_OnUpdateContentStyle__DelegateSignature(EBrickUIColorStyle InColorStyle, EBrickUIStyleState InContentStyleState);
	void BndEvt__WBP_BrickButton_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature();
	void BndEvt__PickObjectsButton_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature();
	void UpdateSelectedObjects(const class FText& FirstObjectName, int32 NumSelectedObjects, bool bDefaultObjects);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_BrickEditorObjectProperty_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_BrickEditorObjectProperty_C")
	}
	static class UWBP_BrickEditorObjectProperty_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_BrickEditorObjectProperty_C>();
	}
};
DUMPER7_ASSERTS_UWBP_BrickEditorObjectProperty_C;

SDK_NAMESPACE_END
