#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BoolProperty

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_BoolProperty.WBP_BoolProperty_C
// 0x0000 (0x0288 - 0x0288)
class UWBP_BoolProperty_C final : public UBoolPropertyWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_BoolProperty_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_BoolProperty_C")
	}
	static class UWBP_BoolProperty_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_BoolProperty_C>();
	}
};
DUMPER7_ASSERTS_UWBP_BoolProperty_C;

SDK_NAMESPACE_END
