#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UGCBrowser

#include "Basic.hpp"

#include "FluUGC_structs.hpp"
#include "Engine_structs.hpp"
#include "BrickRigs_structs.hpp"
#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_UGCBrowser.WBP_UGCBrowser_C
// 0x0048 (0x03B0 - 0x0368)
class UWBP_UGCBrowser_C final : public UUGCBrowserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0368(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	EPlayerSpawnResult                            Can_Spawn_Result;                                  // 0x0370(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_371[0x3];                                      // 0x0371(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Num_Bricks;                                        // 0x0374(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVehicleSpawnProperties                SpawnProps;                                        // 0x0378(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	bool                                          Can_Spawn;                                         // 0x0390(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_391[0x7];                                      // 0x0391(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Spawn_Failure_Text;                                // 0x0398(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_WBP_UGCBrowser(int32 EntryPoint);
	void VoteDown();
	void RemoveItem();
	void AddItem();
	void CreateAddOrRemoveItemButton(bool bIsArrayProperty, bool bIsSelected);
	void CreateSpawnInvincibilityButton(const class FText& CurrentInvincibilityText);
	void CreateOpenInExplorerButton();
	void OnClickedSaveOverwrite();
	void OnClickedSaveNew();
	void CreateSaveOverwriteButton();
	void CreateSaveNewButton();
	void OnClickedUpdateExisting();
	void OnClickedUploadNew();
	void CreateUpdateExistingButton();
	void CreateUploadNewButton();
	void CreateRecoverAutoSaveButton();
	void OnClickedReplaceCurrent();
	void OnClickedSpawnNew();
	void CreateImportButton();
	void OnClickedUnfavorite();
	void OnClickedFavorite();
	void OnClickedUnsubscribe();
	void OnClickedSubscribe();
	void OnClickedCancel();
	void CreateCancelButton();
	void VoteUp();
	void CreateVoteButtons(const EFluUGCItemVote Vote);
	void CreateViewInBrowserButton();
	void CreateSubscribeButton(bool bIsSubscribed);
	void CreateSpawnButton(bool bCanReplaceCurrent, bool bCanSpawn, const class FText& SpawnFailureText);
	void CreateNewItemButton();
	void CreateFavoriteButton(bool bIsFavorited);
	void CreateEditButton();
	void CreateDuplicateButton();
	void CreateDeleteButton();
	void CreateClearItemsButton(bool bIsArrayProperty);
	bool GetSpawnButtonTooltipContent(struct FTooltipContent* OutContent);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_UGCBrowser_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_UGCBrowser_C")
	}
	static class UWBP_UGCBrowser_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_UGCBrowser_C>();
	}
};
DUMPER7_ASSERTS_UWBP_UGCBrowser_C;

SDK_NAMESPACE_END
