#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PropertyCategory

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_PropertyCategory.WBP_PropertyCategory_C
// 0x0020 (0x0298 - 0x0278)
class UWBP_PropertyCategory_C final : public UPropertyCategoryWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0278(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBrickBorder*                           NameBorder;                                        // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBrickTextBlock*                        NameTextBlock;                                     // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBrickGridPanel*                        PropertiesPanel;                                   // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_PropertyCategory(int32 EntryPoint);
	void AddPropertyContainerWidget(class UPropertyContainerWidget* Widget);
	void UpdatePropertyContainerWidgetSlot(class UPropertyContainerWidget* Widget, int32 Index_0, int32 NumPerRow);
	void UpdateCategory(const class FText& DisplayName);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_PropertyCategory_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_PropertyCategory_C")
	}
	static class UWBP_PropertyCategory_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_PropertyCategory_C>();
	}
};
DUMPER7_ASSERTS_UWBP_PropertyCategory_C;

SDK_NAMESPACE_END
