#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_DashboardSlider

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_structs.hpp"
#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_DashboardSlider.WBP_DashboardSlider_C
// 0x0018 (0x0288 - 0x0270)
class UWBP_DashboardSlider_C final : public UDashboardSliderWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0270(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBrickBorder*                           IconBorder;                                        // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBrickImage*                            IconImage;                                         // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_DashboardSlider(int32 EntryPoint);
	void UpdateColorStyle(EBrickUIColorStyle NewStyle);
	void UpdateIcon(int32 IconIndex);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_DashboardSlider_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_DashboardSlider_C")
	}
	static class UWBP_DashboardSlider_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_DashboardSlider_C>();
	}
};
DUMPER7_ASSERTS_UWBP_DashboardSlider_C;

SDK_NAMESPACE_END
